name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn check
      - run: yarn format:check
      - name: Build android
        run: |
          export KEYSTORE_PASS=$(node -e 'console.log(require("crypto").randomBytes(64).toString("hex"))')
          export KEYSTORE_ALIAS_PASS=$(node -e 'console.log(require("crypto").randomBytes(64).toString("hex"))')
          ( cd android/keys && ./generate.sh )
          yarn build:android
          cp android/app/build/outputs/apk/release/app-release-signed.apk android/app/build/outputs/apk/release/question.apk
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: android/app/build/outputs/apk/release/question.apk
